name: SurvivalClasicCore
version: '${project.version}'
main: net.eternaln.survivalclasiccore.SurvivalClasicCore
api-version: 1.19
authors: [ Aitooor, EternalTeam, Vicen621 ]
description: Simple core plugin for Eternal Network Survival Clasic
softdepend:
  - PlaceholderAPI
libraries:
  - org.projectlombok:lombok:1.18.24
  - com.github.cryptomorin:XSeries:9.0.0
  - org.mongodb:mongodb-driver-sync:4.6.0

permissions:
  survivalclasic.staffmode.onjoin:
  survivalclasic.homes.max:
    description: "Set <permision>.max.<number> to set the max amount of homes a player can have."